### PR TITLE
fix

### PR DESCRIPTION
**Pull request by vadim9999**

### CODE REVIEW

**Comment by atherdon** [comment]
we cannot wrap {renderItem} with `<li>` because this will destroy our abilities to have lists with `<div>`s for example.

btw, adding you as collaborator to this repo - so you'll be able to merge code by yourself

**Comment by atherdon** [comment]
don't forget to publish it to npm

**Comment by vadim9999** [comment]
Without wraping  {renderItem} with `<li>` it returns error

**Comment by atherdon** [comment]
got it. then we should find another way how to do it without wrapping by <li

**Pull request merged**
